### ISSUE TITLE
*NEW* Make mentoring page 

### ISSUE THREAD

**Issue by vuzDylan** [rit-sse/OneRepoToRuleThemAll#10]

**Comment by 7imbrook** [comment]
A note about functionality, we have concurrent mentoring now and also not all shifts are 2 hour blocks.

**Comment by kristenmills** [comment]
It supports multiple people in the same shift.
I'll have to figure something out for non 2 hour blocks.

**Comment by vuzDylan** [comment]
is this done?

**Comment by 7imbrook** [comment]
no

**Comment by kristenmills** [comment]
Yeah. We need scrap react-big-calendar.

**Comment by billdybas** [comment]
Slated for removal in #163
