### ISSUE TITLE
There is some weird horizontal scrolling on officers on mobile. 

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/OneRepoToRuleThemAll#103]
I don't like it.

**Comment by vuzDylan** [comment]
Oh WTF

**Comment by vuzDylan** [comment]
Weird

**Comment by vuzDylan** [comment]
I just went to fix this and I can't reproduce it (It does behave bad when you resize it for some reason but on a load on mobile it works fine)

**Comment by kristenmills** [comment]
Maybe it's only a problem on iOS. I can consistently reproduce.

**Comment by kristenmills** [comment]
I'll assign to myself...I'll look at it later.

**Comment by wadeanthony0100** [comment]
Just throwing a data point out there, I see nothing unexpected on my phone (iPhone 6s the smaller one, iOS 10.3.2) on both Safari and Chrome. Maybe I just don't know what to look for?

**Comment by kristenmills** [comment]
![img_0534](https://cloud.githubusercontent.com/assets/1054558/26500327/5834d6aa-41ea-11e7-8098-ccf4c5675a1f.PNG)
![img_0535](https://cloud.githubusercontent.com/assets/1054558/26500326/58344c44-41ea-11e7-9a75-fd8df2c4e0a8.PNG)

**Comment by wadeanthony0100** [comment]
Oh, I guess I see that, but only on the right just a little
![18721523_1302671569786210_976639545_o](https://cloud.githubusercontent.com/assets/7254185/26500555/595b65d4-4204-11e7-9c73-38a325c072b4.jpg)

**Comment by vuzDylan** [comment]
ya okay I see this on the right but not the left... although I have no idea what's happening on the right... for some reason the rows are 10px larger than the container and it makes no sense

**Comment by vuzDylan** [comment]
oh wait I'm really dumb I did this ill fix it
