### ISSUE TITLE
Officers get deleted without confirmation

### ISSUE THREAD

**Issue by wadeanthony0100** [rit-sse/OneRepoToRuleThemAll#104]
I deleted @djrenren completely by accident in production without an "Are you sure about this?".

I think It would be nice to have something preventing accidental loss, even though it's a restricted action.

**Comment by vuzDylan** [comment]
Oh boy I have a cool idea for this

**Comment by wadeanthony0100** [comment]
What's that?

**Comment by vuzDylan** [comment]
welp my idea sucked prob just gona make a modal now
