### ISSUE TITLE
Site does not load or display an error when JavaScript is disabled

### ISSUE THREAD

**Issue by nickmccurdy** [rit-sse/OneRepoToRuleThemAll#109]
Many users need to keep JavaScript disabled, and either way not having content available without JavaScript hurts SEO. Since you're already using React this should be easy, generate a Node bundle with webpack and hydrate the React components to render them on a server side framework before the client is hydrated (use `ReactDOM.renderToString` on the server).

**Comment by vuzDylan** [comment]
correct
