### ISSUE TITLE
GTV 

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/OneRepoToRuleThemAll#11]
Turn trash into shinier  trash

**Comment by kristenmills** [comment]
GTV is a reminder that I too can be very very shitty.

**Comment by 7imbrook** [comment]
pls move to /gtv even if it is trash

**Comment by kristenmills** [comment]
Fine.

**Comment by 7imbrook** [comment]
Also is just a white screen on the GTV

**Comment by kristenmills** [comment]
Wait actually?

**Comment by kristenmills** [comment]
I'm going to open a separate issue for that. And assign it to you and dylan. Because I don't have the required hardware to repro

**Comment by 7imbrook** [comment]
No I expect you to go by an old tv off of ebay, get with the program or you're fired.
