### ISSUE TITLE
Officers creation error messages are not correct

### ISSUE THREAD

**Issue by wadeanthony0100** [rit-sse/OneRepoToRuleThemAll#111]
Not sure if this is a problem with node-api's errors, or the way OneRepo handles them, but when trying to create an officer, omitting a committee, when 'is primary' was checked, yielded the following error.
![image](https://user-images.githubusercontent.com/7254185/27447787-43f71510-5737-11e7-977b-3ff6610bf6df.png)
This is a little confusing because the first and last name fields were filled.

**Comment by vuzDylan** [comment]
You need to give a primary officer a committee we usually give it general. This is the correct error message and unless we wana fix sequelize this is the error message we get

**Comment by wadeanthony0100** [comment]
Why? why not post general when primary is selected regardless then?

**Comment by vuzDylan** [comment]
hmm okay I see what happened

**Comment by wadeanthony0100** [comment]
Could you share what the issue is?

**Comment by vuzDylan** [comment]
The field got set to null when it should be set to undefined and javascript handles those two things differently when posting that data

**Comment by vuzDylan** [comment]
Okay so this is a bug on API according to kristen committee name is a 'required field' as of this moment. So im going to implement you solution of putting all primaries in the General Committee
