### ISSUE TITLE
Officers should have some implicit hierarchy 

### ISSUE THREAD

**Issue by 7imbrook** [rit-sse/OneRepoToRuleThemAll#115]
President should be listed first followed by VP. It definitely shouldn't be last.

https://sse.rit.edu/officers

**Comment by kristenmills** [comment]
see rit-sse/officers#6 for what it should look like.

**Comment by billdybas** [comment]
I would agree some hierarchy would be nice. Additionally, whatever is created should be responsive on mobile and not cut off email addresses like it currently does.

**Comment by wadeanthony0100** [comment]
I suddenly feel this issue should be prioritized 😏 @billdybas ??? 🤷‍♂️  🤷‍♂️  🤷‍♂️

**Comment by billdybas** [comment]
Gladly accepting pull requests. 😉
