### ISSUE TITLE
GTV has some caching issues

### ISSUE THREAD

**Issue by wadeanthony0100** [rit-sse/OneRepoToRuleThemAll#117]
Not sure if this is the right place for this, but the GTV app seems to be caching requests far longer than we would like. When Tina changed the times of events, the GTV continues to display the old times even a few days later.

**Comment by kristenmills** [comment]
Hmmm that's new. It's supposed to refresh every 30 seconds.

**Comment by wadeanthony0100** [comment]
Could it have anything to do with running it on chromium / ras pi vs directly on the GTV?

**Comment by kristenmills** [comment]
I don't think so. But if you want to check the console logs and network requests on chromium, that might shed some light.

**Comment by wadeanthony0100** [comment]
We tried that, but the distro we're using to runs chromium and seems to disable accessing those features... But other people are welcome to try.

The other thought we had was to restart the pi and see if the server logs shed any light (If we have server logs).

**Comment by wadeanthony0100** [comment]
Can we close this one?

**Comment by vuzDylan** [comment]
Sure
