### ISSUE TITLE
Social Page 404's

### ISSUE THREAD

**Issue by billdybas** [rit-sse/OneRepoToRuleThemAll#120]
On the [About page](https://github.com/rit-sse/OneRepoToRuleThemAll/blob/devlop/app/markdown/about.md), there's a link that goes to `https://sse.rit.edu/social`, but that page doesn't exist. 

It did exist in [crazy-train](https://github.com/rit-sse/crazy-train-pages/blob/master/about/social.html) - do we want a social page again, or remove this link?

**Comment by vuzDylan** [comment]
That page looks like it contains a lot of outdated information. If we want to make a new one just make a markdown file called social.md and put it in the markdown folder and it will magically work.

**Comment by wylaris** [comment]
What do you want on that page?  Links?  Embedded social media?

**Comment by vuzDylan** [comment]
I have no idea that's why I haven't done it yet

**Comment by wylaris** [comment]
I'll look into possibilities and create a markdown for it.

**Comment by wylaris** [comment]
Created a markdown page and made a pull request, will need help with a merge conflict.

**Comment by vuzDylan** [comment]
Currently on dev

**Comment by billdybas** [comment]
Fixed via #145
