### ISSUE TITLE
Scoreboard: View Personal Membership Details link

### ISSUE THREAD

**Issue by wadeanthony0100** [rit-sse/OneRepoToRuleThemAll#121]
There's no visual indication that clicking on a row on scoreboard will bring anything up. Some sort of on-hover effect would be useful

**Comment by billdybas** [comment]
Reminder for me:

https://github.com/rit-sse/OneRepoToRuleThemAll/blob/devlop/app/scss/member.scss

```sass
.member {
    &:hover {
        cursor: pointer;
    }
}
```

Might also want to lighten / darken the table row which is currently hovered over.
