### ISSUE TITLE
On Error, Form is erased

### ISSUE THREAD

**Issue by akath20** [rit-sse/OneRepoToRuleThemAll#124]
When there is an error, formed is erased and needs to be typed all over again

**Comment by vuzDylan** [comment]
Does this still happen? I just pushed a bunch of fixes and not sure if this was fixed.

**Comment by vuzDylan** [comment]
Anyone? had this happen recently? if not Im closing this because I think I might have fixed it

**Comment by akath20** [comment]
I thought someone did it this week and it happened. I would need to check

**Comment by wadeanthony0100** [comment]
This does still happen, I just tested in prod

**Comment by vuzDylan** [comment]
okay sounds good

**Comment by billdybas** [comment]
We did a major form overhaul in #162, and all forms will now do client-side validation on fields. This should catch common user errors from occurring before form submission. And errors w/ a partiicular field will not cause other fields to be cleared. 

However, if there are server-side issues, one _will_ continue to have to re-enter and re-submit the form.

If you continue to find any issues related to this once we merge `devlop` into `master`, feel free to re-open this issue or make another, more-specific issue.
