### ISSUE TITLE
Mentoring and projects committee links lead nowhere

### ISSUE THREAD

**Issue by Scott-Frauenknecht** [rit-sse/OneRepoToRuleThemAll#135]
Links in the about tab for Mentoring committee and for the projects committee lead nowhere. The mentoring committee link should probably lead to a schedule I'm guessing for mentors and the projects committee should probably lead to the projects tab.

**Comment by billdybas** [comment]
Thanks for your keen eye!

The projects link has already been fixed (in development) [See [PR #132](https://github.com/rit-sse/OneRepoToRuleThemAll/pull/132)]

We used to have a mentoring page but removed it temporarily [See 17728d84fad634e97f3c7d4d81baf2d08f57397f]. We're working on a long-term solution for the mentoring page [See #131].

A temporary solution is removing the link on "Mentoring Committee." Go ahead and submit a PR which removes this link - this is a great first PR if you've never worked on our codebase before (and you'll get credit for [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!). Make sure to branch off of devlop when making the fix.
