### ISSUE TITLE
Ambiguous QDB Errors

### ISSUE THREAD

**Issue by wadeanthony0100** [rit-sse/OneRepoToRuleThemAll#137]
I get this error when I try to make or approve quotes:

<img width="1141" alt="screen shot 2017-10-11 at 4 54 13 pm" src="https://user-images.githubusercontent.com/7254185/31466402-0a3316ba-aea5-11e7-8163-ec6d2097d879.png">

**Comment by vuzDylan** [comment]
#fixed it

**Comment by wadeanthony0100** [comment]
What was the problem, if I may ask?
