### ISSUE TITLE
Technology Request Form

### ISSUE THREAD

**Issue by billdybas** [rit-sse/OneRepoToRuleThemAll#144]
It'd be neat and useful to have a tech request form which people fill out for:
- Requesting to be added to the GitHub organization, Docker Hub organization, etc.
- Requesting certain secrets or permission changes (eg. on our social media)
- Requesting new repo's for projects
- CI / CD requests

MVP would be when this form is submitted, the contents would be posted in our Slack channel.

Stretch goal would be adding an authenticated page which shows all tech requests which have been made and whether they are pending or complete (this would also require API changes).

**Comment by 7imbrook** [comment]
#googleForms

**Comment by kristenmills** [comment]
Yeah no need to reinvent the wheel here. Google forms would be better suited

**Comment by billdybas** [comment]
Yeah, using a Google Form for now. Currently sends me emails, though it'd be nice if it were Slack notifications instead.

**Comment by kristenmills** [comment]
https://gist.github.com/andychase/e0b1eaa1b9ecc00ef2d2
