### ISSUE TITLE
The events form should have some input validation.

### ISSUE THREAD

**Issue by wadeanthony0100** [rit-sse/OneRepoToRuleThemAll#148]
Or should at least keep the inputs filled unless a submission is successful.

<img width="1151" alt="screen shot 2017-11-03 at 1 38 11 pm" src="https://user-images.githubusercontent.com/7254185/32387912-53bafeca-c09c-11e7-972d-d986112ac588.png">

**Comment by vuzDylan** [comment]
You should have added the start date before end date validation in this one too

**Comment by billdybas** [comment]
The node-api checks this already, but I can add this if you'd like me to.
