### ISSUE TITLE
Having buttons always visible looks really bad on officers

### ISSUE THREAD

**Issue by vuzDylan** [rit-sse/OneRepoToRuleThemAll#152]
It covers the officers title

**Comment by billdybas** [comment]
Good catch. I've never been a primary, so I didn't even know that page had actions. I'll figure out a fix.

**Comment by vuzDylan** [comment]
I'm not too sure about this being a solution... you have to hover over where the buttons are to see them which implies that you know where the buttons are which is confusing

**Comment by billdybas** [comment]
I was reverting the changes I made in #150 for this particular page and misread that the hover styles were actually on the `action-container`. I should probably stop trying to fix bugs at 1 AM.
