### ISSUE TITLE
Clear status on route transition

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/OneRepoToRuleThemAll#21]
Uh dylan you are better at React-router 4 than me. Assigning to you.

**Comment by 7imbrook** [comment]
assuming we're using router-redux-location then we should be able to do that with his status middleware

**Comment by kristenmills** [comment]
router-redux-location?

**Comment by 7imbrook** [comment]
yeah I think thats some npm library that combines a bunch of node technologies

**Comment by 7imbrook** [comment]
*todo something simple. How could I forget the most important part

**Comment by kristenmills** [comment]
Helpful

**Comment by vuzDylan** [comment]
Um we are using like mega super beta software so this mught not be a thing yet. I am currently trying to figure out how to do this

**Comment by kristenmills** [comment]
We can totally do it if we listen to changes on history or specify the user confirmation function. It's just a matter of where.

**Comment by kristenmills** [comment]
`context.history` is a thing so we can technically do it anywhere inside the router but I couldn't pin point a good spot.

**Comment by kristenmills** [comment]
Also you could user a regular `<Router>` instead of `<BrowserRouter>`, then we can provide our own `history` which we could import anywhere.

**Comment by vuzDylan** [comment]
That last one is what I think Im going to do I kinda wana write somthing like how react-router-redux worked

**Comment by vuzDylan** [comment]
but ill finish QDB first

**Comment by vuzDylan** [comment]
Also need to fix the freaking drop down on mobile collapsing on route change
