### ISSUE TITLE
Add version stamp to footer

### ISSUE THREAD

**Issue by wadeanthony0100** [rit-sse/OneRepoToRuleThemAll#213]
Verifying a redeploy happened can be annoying, we could have a little stamp in the footer to make it just a little easier.

**Comment by kristenmills** [comment]
Two cents: Add an endpoint that will show you the current commit deployed, the circle ci build, and the date deployed. Or something like that.

**Comment by wadeanthony0100** [comment]
My thinking here was just for OneRepo's sake, to statically show the short commit sha or something, independent of node-api.

Are you saying to do that in place or in addition to this?

**Comment by kristenmills** [comment]
in place of. It seems weird to show it on the website itself.

**Comment by akath20** [comment]
<img width="601" alt="image" src="https://user-images.githubusercontent.com/6372519/45322840-6a792680-b517-11e8-92b5-904af212ea69.png">
An idea of what it might look like at the bottom.
