### ISSUE TITLE
Show Information on Setting Up Events Feed w/ Personal Calendar

### ISSUE THREAD

**Issue by bquinn17** [rit-sse/OneRepoToRuleThemAll#214]
This way it can easily be synced with your personal calendar. Works with Goolge calendar, Apple, etc.

**Comment by billdybas** [comment]
We have this. You can point the calendar to https://sse.rit.edu/api/v2/events.ics

We should make this visible on the events page that you can do this.

**Comment by kristenmills** [comment]
There used to be an icon on the events page and I wanna say the social page but they probably got lost with the move to one repo. Definitely should add it back
