### ISSUE TITLE
Do something about hover on mobile

### ISSUE THREAD

**Issue by vuzDylan** [rit-sse/OneRepoToRuleThemAll#22]
Events is currently an offender

**Comment by kristenmills** [comment]
Long press with bottom sheet for edit and delete? Mentoring is also an offender for the same reason

**Comment by vuzDylan** [comment]
I was thinking maybe a swipe thing idk yet

**Comment by kristenmills** [comment]
Makes sense for events. Won't work for mentoring if I keep that a horizontal list on mobile. I'll figure that one out.

**Comment by kristenmills** [comment]
Mentoring and Officers need a hover solution too. But swipe is not suitable for those.

**Comment by kristenmills** [comment]
Probably going to do long press for those.

**Comment by 7imbrook** [comment]
gross

**Comment by kristenmills** [comment]
Do you have a better suggestion?

**Comment by 7imbrook** [comment]
no, but it seems gross

**Comment by kristenmills** [comment]
Officers is now a single column list on mobile, swipe will be fine probably.
