### ISSUE TITLE
Update 404 Page not Found

### ISSUE THREAD

**Issue by akath20** [rit-sse/OneRepoToRuleThemAll#225]
<img width="1556" alt="image" src="https://user-images.githubusercontent.com/6372519/46494620-48ef2000-c7e1-11e8-8b2b-df80bbe5bbb8.png">
It would be nice to update this into something that looks a little nicer. It does the job, but maybe would be a good first issue for someone to remake this with maybe a larger, icon-based 404 page.

**Comment by AllUsernamesHaveBeenTaken** [comment]
Can I tackle this one?

**Comment by billdybas** [comment]
@AllUsernamesHaveBeenTaken Sure! What were you thinking? Did you want to draw or mock something up first and post an image?

**Comment by AllUsernamesHaveBeenTaken** [comment]
This is what it looks like on mobile.
![404-on-mobile](https://i.imgur.com/HooUczf.png)
