### ISSUE TITLE
Getting an error when creating an event

### ISSUE THREAD

**Issue by bquinn17** [rit-sse/OneRepoToRuleThemAll#231]
I don't think there's really anything special about this event, but every time I try to create it I get the following error:

<img width="378" alt="event" src="https://user-images.githubusercontent.com/14142655/46706668-bcd76100-cc03-11e8-8f44-008fb0ec5d10.PNG">
<img width="342" alt="eventserror" src="https://user-images.githubusercontent.com/14142655/46706670-c1037e80-cc03-11e8-9868-6e34459ba373.PNG">

And this message is printed to the console: `Failed to load resource: the server responded with a status of 422 ()`

**Comment by akath20** [comment]
At first glance of debugging this, this may be a side effect of upgrading our dependencies recently.

**Comment by billdybas** [comment]
@akath20 I think this is a good bug for you to debug. 

The error message looks like something Sequelize, so I'd see what's up with that in the node-api.
See if you can reproduce and have the Docker logs up to see what Sequelize is complaining about.

I'd also see whether upgrading Formik made our form no longer submit correctly.

**Comment by akath20** [comment]
Update: Issue seems to be from node-api, however nothing was recently done to it. It seems like the recent dependency update is *likely* not the issue seeing how memberships were successfully added after that was pushed.

Going to try to redeploy node-api and reproduce locally. We can roll-back, but doesn't seem like that would do much.

**Comment by wadeanthony0100** [comment]
Maybe relevant: https://www.postgresql.org/message-id/AANLkTims48njGKkvkXHiTG6%3D19hQ31VFmFRPPLg%2B5w03%40mail.gmail.com

**Comment by billdybas** [comment]
😬 Corrupted log doesn't sound good. If we can, I'd suggest doing a backup dump of the prod db before we do anything.

**Comment by akath20** [comment]
I have the backup on the server and on my local machine. However, when I was copying it out of the container I got an error that the host ran out of space which might be the issue. 

`/dev/mapper/eggs--vg-root   81G   79G     0 100% /`

I am not sure what this is, but will look into reducing the storage on the server.

**Comment by billdybas** [comment]
Wow, that’s really strange. I wonder what’s taking up so much space on the server.

**Comment by akath20** [comment]
Old Docker images and caches. Currently running `docker system prune` and it’s going down in storage.

**Comment by akath20** [comment]
Still running the command, but this successfully fixed the issue.
