### ISSUE TITLE
Displaying Go Links To The Public

### ISSUE THREAD

**Issue by saf6260** [rit-sse/OneRepoToRuleThemAll#246]
#85 was an issue brought up by Kristen but never happened. I think this would be really valuable to members who don't check the slides often to find our go links. Plus, our go links are normally links to forms, where the form are blocked to only allow individuals who have an RIT account to access them.

We can also add a description box to the go link allowing for visitors to know what the go link is about. 

Does anyone have thoughts about this? As Wade pointed out this would be an opt-in system.

**Comment by bquinn17** [comment]
We have gotten several requests from members to increase the visibility of the SSE outside of just the officers. One of the requests as part of this was to make a list of go links visible to non-officers. This is the main motivation behind bringing up this issue again.

**Comment by billdybas** [comment]
I think we could add a field to the go links to mark them as public, indicate that on the go link form, and then show those public links on that page to non-authors people.

**Comment by saf6260** [comment]
Fixed with #247
