### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by 7imbrook** [rit-sse/OneRepoToRuleThemAll#3]

**Comment by kristenmills** [comment]
On the topic of QDB in the nav, we've talked about it several times over my years in the SSE and the general consensus has always been we don't want QDB actually linked to on the main site because some quotes are NSFW.

**Comment by vuzDylan** [comment]
YUP The nav is there for me to get around right now

**Comment by vuzDylan** [comment]
This issue will close when the website is polished
