### ISSUE TITLE
Store quotes as an object instead of an array

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/OneRepoToRuleThemAll#30]
We have lots of quotes.  Many hundreds so we should store them in a way that lookup can be o(1) instead of o(n). See mentors or officers for an example.

**Comment by 7imbrook** [comment]
why?

**Comment by kristenmills** [comment]
For updating quotes.

**Comment by 7imbrook** [comment]
sparse array? aka ord dict

**Comment by kristenmills** [comment]
Object. Id key, value quote.

**Comment by 7imbrook** [comment]
but ordering :P

**Comment by vuzDylan** [comment]
ya wont it end up being worse if i have to like sort it or something
If this ever becomes a problem I can change the function to pass the index instead of the ID

**Comment by kristenmills** [comment]
No it wont. You can always get it as an array using Object.values.

**Comment by kristenmills** [comment]
And when do you need to sort it anyway?

**Comment by kristenmills** [comment]
It's already sorted by id

**Comment by vuzDylan** [comment]
fine.

**Comment by vuzDylan** [comment]
actually no this will absolutly no performance gain given that for a delete I will now have to either copy the object and delete a value (setting the object to slow mode which is very bad) or I can set it to undefined and filter out undefined when I re render the quotes which will be an 0(n) operation...

**Comment by kristenmills** [comment]
You don't have to delete. 

`const { [action.payload.id] , ...rest } = state;`

**Comment by vuzDylan** [comment]
I actually dont even thing using find is that bad. The only time that all 900+ quotes will be in the reducers is if someone just sits there scrolling down and then wants to edit. If they search then you wont have nearly as many quotes in the store. and lets be honest how long does it really take to iterate though a list once even if that list has 900+ entires

**Comment by vuzDylan** [comment]
ya like i just ran a test of a list with 100,000 elements and a find took .15s so like it dosn't matter at all

**Comment by vuzDylan** [comment]
like thats less time then it takes to display the modal
