### ISSUE TITLE
User form sometimes doesn't autofill

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/OneRepoToRuleThemAll#32]
Not sure why but sometimes it makes the request to get the user but doesn't populate the fields.

**Comment by vuzDylan** [comment]
I saw this happen and i'm so confused

**Comment by vuzDylan** [comment]
welp I just tried to get it to not work and I couldn't I give up

**Comment by vuzDylan** [comment]
This randomly happened to me again last night but then I couldn't make it happen again

**Comment by vuzDylan** [comment]
I think I know why this happens I will investigate at some point
