### ISSUE TITLE
Login Button should be in the nav. 

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/OneRepoToRuleThemAll#47]
Seems silly to login in on each app.

**Comment by vuzDylan** [comment]
you don't have to login on each app the login will persist and we had lots of discussion about not wanting to put login in  the nav (i still think its good but some people don't want it)

**Comment by kristenmills** [comment]
Idk I just don't like it being unique on each page. I know you login once it's done. But I think it looks silly.

**Comment by vuzDylan** [comment]
Im changing this to a discussion issue though nevertheless

**Comment by kristenmills** [comment]
That seems fine

**Comment by 7imbrook** [comment]
I still vote that it's hidden at like /login because only a few people need to know how to use it. And if we can get loggin to persist for like a month or so it should be fine.

**Comment by kristenmills** [comment]
Dylan and I were talking about that and I wasn't a huge fan. 

1. Members can log in for QDB and the future revival of Me. So now everyone has to know about this hidden login page. 

2. Also General usage of the SSE website is not really through a navbar, everyone know the URLs to every app and goes directly there. 

So the usecase becomes 
1. navigate to /go out of habit
2. See I'm not logged in
3. navigate to login
4. login
5. navigate back to /go

And that would annoy me.

**Comment by vuzDylan** [comment]
I really dont think its awful the way it is I would like it in the navbar though because I think that would look better

**Comment by vuzDylan** [comment]
I guess we are just gona leave it the way it is unless some one in the future has a strong opinion
