### ISSUE TITLE
Tag page doesn't show any quotes

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/OneRepoToRuleThemAll#48]

**Comment by kristenmills** [comment]
https://github.com/rit-sse/node-api/blame/devlop/routes/quotes.js#L23 That's wrong. That's my bad.

**Comment by vuzDylan** [comment]
Did you ever fix this?

**Comment by kristenmills** [comment]
No I forgot yesterday. Uh if you want to just do it, Look at the git blame and see what the line used to be and replace the line. (Don't just revert the commit...there were other things in that commit)

**Comment by vuzDylan** [comment]
okay ill check it out

**Comment by vuzDylan** [comment]
@kristenmills Reverting that line doesn't fix it

**Comment by vuzDylan** [comment]
I made it return [count, Promise.map(result.rows, quote => quote.reload({ include: [{ model: Tag, attributes: ['name'] }] }))];

**Comment by vuzDylan** [comment]
Like its being weird it's putting 10 quotes on 7 pages

**Comment by kristenmills** [comment]
Fuck Idk what's wrong. I'll look at it in a second.

**Comment by kristenmills** [comment]
https://github.com/rit-sse/node-api/commit/3be8a508eb9caa37af8d2578b9d6fa9f867b8a2b#diff-138f06bb522d5678a77f3fbd2779d388

Try adding that back too.

**Comment by kristenmills** [comment]
I swore I tested that and found it unnecessary anymore. Guess I'm wrong and or garbage.

**Comment by kristenmills** [comment]
Those are the only two changes to quote within the past year.

**Comment by vuzDylan** [comment]
Okay that fixed it :+1:
