### ISSUE TITLE
Constitution margins are dumb

### ISSUE THREAD

**Issue by robmcl4** [rit-sse/OneRepoToRuleThemAll#53]
The margins on the constitution's page are wrong. Bullets are not indented. See included image below:
![constitution](https://cloud.githubusercontent.com/assets/884115/25880004/b6c4ff96-3502-11e7-91b3-2eaee92c014c.PNG)

**Comment by billdybas** [comment]
`list-style-position: inside;`
https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position
