### ISSUE TITLE
Two VP's on Officers Page

### ISSUE THREAD

**Issue by Michael-Longley** [rit-sse/OneRepoToRuleThemAll#55]
Wade and Timbrook are both showing up on the officer's page. 

![image](https://cloud.githubusercontent.com/assets/15826968/25901038/73d10dae-3563-11e7-9b24-9799eff67206.png)

**Comment by vuzDylan** [comment]
Ya one of the primaries added wade as VP

**Comment by Michael-Longley** [comment]
Ok, just wanted to make sure it was intentional.
