### ISSUE TITLE
Doesn't Work With Old Browsers

### ISSUE THREAD

**Issue by billdybas** [rit-sse/OneRepoToRuleThemAll#60]
I've tested the new site in IE 11 and Safari 8.

There are two very noticeable issues:

1. Styling is messed up on Safari - if we're using flexbox, it's likely because flexbox in old Safari requires a vendor prefix

2. Data fetching is broken on IE and Safari. The spinner just keeps spinning and nothing happens. IE's console complains that "'Promise' is undefined". This means events don't load on the homepage and no other page will load.

**Comment by vuzDylan** [comment]
0.8% of all people on the internet are using safari 9 or older so I don't think that is a problem (works in safari 10+) I'll put a polyfill in for Promises because IE 10 + is like 14% so I guess that matters
