### ISSUE TITLE
Specify the client URL to an environment variable

### ISSUE THREAD

**Issue by jcdesimp** [rit-sse/OneRepoToRuleThemAll#66]
OpenGraph demands canonical URLs for the `og:url` and `og:image` properties. This requires that the URL of the hosted webpack bundle be known at web pack build time.

This would make the resulting bundle targeted for a specific environment and no longer directly portable.

However it will allow for proper open graph meta tag configuration enabling shared links to our site to look much prettier. 

Currently they look like this:
<img width="730" alt="screen shot 2017-05-10 at 6 52 16 pm" src="https://cloud.githubusercontent.com/assets/3452966/25929075/f2ce4fc6-35cd-11e7-90d0-abef00d4da6c.png">

With OG we could specify the title and put a nice image in there.

**Comment by 7imbrook** [comment]
Here on the reason discussed OOB:
- Builds need to be forward looking, which breaks the same artifact multi environment principle. And I'm strongly against this because for once we actually have this and it's invaluable.
- Introducing any server side content generation means we've broken OneRepos static advantage.
- Moving away from just static-client/api relationship warrants a lot of discussion about worthiness. Along with implementation choice. Do we use php script it? Do we use a jank nginx module? Every decision moves us away from the simplicity of it all. 

I like this feature and it would be nice, but as of right now, I don't think it's worth breaking what we have currently in terms of build.

**Comment by jcdesimp** [comment]
@7imbrook in what ways is it "invaluable"? What is the practical advantage to it right now? I see an end product advantage to changing this, but I don't see one to keeping the build not forward looking. Only disadvantage is needing to change a single environment variable when we redeploy to a new environment/domain but I personally like for this to be what our links look like.

<img width="568" alt="screen shot 2017-05-10 at 11 01 25 pm" src="https://cloud.githubusercontent.com/assets/3452966/25930528/c42a35c0-35d4-11e7-8c52-4062d68e89f8.png">

It's a minor thing, so if people don't think its worth having to set a new build variable and target our builds then thats fine. IMO end product enhancements are worth minor developer inconveniences.

**Comment by 7imbrook** [comment]
@jcdesimp a correction you may want to consider, by the time we know where we're deploying the webpack build has happened. The same build can run in dev or prod. It doesn't do us any advantage to specify the runtime location after this for static assets. As for the advantage of static assets. Heavy caching and easy server load. I know this isn't a big deal for the sse webpage but it's something to consider. 

Ultimately I can see it going the way of release build vs dev builds for each environment, but for the sake of not giving developers the tool to have the environments diverge is for the better. It's truly the only way to guarantee if it works in dev it works in prod. Ik I'm not making a practical argument, but I'm making it out of principle and best practice, which can act as an invaluable learning tool for  members to come.

**Comment by jcdesimp** [comment]
@7imbrook Fair enough. Seems like it comes down to whether to not it's worth making the bundles targeted to specific environments. Currently I believe this is the only feature that's blocked by it (unless we hard code the prod URL or some other less optimal alternative).

I'll leave it up to you, @vuzDylan,and @billdybas to decide if the feature is worth it.

Server side rendering is probably the "correct" solution to this but for this minor feature probably not worth the overhead IMO.
