### ISSUE TITLE
Cannot add quotes to QDB

### ISSUE THREAD

**Issue by scioffi** [rit-sse/OneRepoToRuleThemAll#67]
When trying to add new quotes to QDB, an update form appears and on submission, tries to update a quote that does not exist yet and a the quote is not added.

**Comment by 7imbrook** [comment]
@scioffi you're aware that quotes need to be approved by primaries right?

**Comment by kristenmills** [comment]
@7imbrook that's not the issue. The issue is the update form shows instead of the create form

**Comment by vuzDylan** [comment]
Ah yes I see the problem

**Comment by kristenmills** [comment]
https://github.com/rit-sse/OneRepoToRuleThemAll/commit/5b7b37742b46903a8fb358ecd9d2baa938257b43

**Comment by kristenmills** [comment]
That's the commit I think broke it. Is events broken too?

**Comment by kristenmills** [comment]
So revert that...and this one 9a4c01a557f083766e363de5c878588b2469a139 and this issue should be fixed.

**Comment by kristenmills** [comment]
Or remove the default props.  I don't think we actually want them.

**Comment by kristenmills** [comment]
@vuzDylan and I talked about it, default props is going to return null. And that's gonna be the fix.
