### ISSUE TITLE
All All All All All

### ISSUE THREAD

**Issue by derekerdmann** [rit-sse/OneRepoToRuleThemAll#71]
The first option on the Events filter links is "All," but the link is repeated 5 times at the end of the list of possible filters. If you switch to another filter, you end up with 6 total links that take you back to "all events."

![capture](https://cloud.githubusercontent.com/assets/592152/25962335/24c85760-3632-11e7-94e0-c512f3b95b5a.PNG)

**Comment by vuzDylan** [comment]
Hmm this is an exciting bug I have no idea why that's happening

**Comment by vuzDylan** [comment]
Steps to repro?

**Comment by kristenmills** [comment]
Navigate to https://sse.rit.edu/events?

**Comment by kristenmills** [comment]
It's a prod specific issue afaik. It didn't look like it was appearing on dev.

**Comment by 7imbrook** [comment]
It's a db issue, moving it to infrastructure maintenance

**Comment by 7imbrook** [comment]
Not a db issue upon further investigation. I believe it to be @vuzDylan  pagination code calling committees endpoint twice.

**Comment by 7imbrook** [comment]
node-api is returning a count of 28 committees on prod, there's only 16 in the db @kristenmills?

**Comment by kristenmills** [comment]
Node api looks to be returning a count of 16. One of which is an empty committee which should be deleted I think?

**Comment by kristenmills** [comment]
Not sure why there are 5 alls. The one with the empty name should cause one extra All

**Comment by 7imbrook** [comment]
If you inspect the network calls, two are made. It's paginating.

**Comment by kristenmills** [comment]
Sure there are two pages.

**Comment by kristenmills** [comment]
Therefore 2 calls are made

**Comment by kristenmills** [comment]
It's fixed.
