### ISSUE TITLE
Go links should be visible when not logged in. 

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/OneRepoToRuleThemAll#85]
All previous iterations of Go have had the links visible to everyone. No real reason to hide them...

**Comment by wadeanthony0100** [comment]
Would we be able to implement this as an opt-in feature? It's kinda nice to be able to make links and only share them with certain groups to minimize spam IMO.

**Comment by kristenmills** [comment]
So I guess so but I don't see the point. 
1. /api/v2/links is a public endpoint. No point in hiding them here...they aren't actually hidden.
2. We've never had problems with displaying go links before. Frankly we used to let anyone create go links...I don't think we should bring that back but just more to the point go link abuse has never been a thing. 

Like I don't really care. It's not necessary to show them, I just don't see any value in hiding them.

**Comment by 7imbrook** [comment]
I don't believe that go should be a place to go discover what links there are, the statement ALL previous iteration is false, for at least the last two years there hasn't been a viewable list of go links for non authorized users. And it should be up to the new officers to weigh in and decide whether to move forward or not on this.

**Comment by kristenmills** [comment]
Well I checked old go, I'm apparently wrong. I totally thought it was visible to everyone. Nevermind.
