### ISSUE TITLE
Add membership should have duration or semester defaults. No date picker it's useless

### ISSUE THREAD

**Issue by 7imbrook** [rit-sse/OneRepoToRuleThemAll#94]

**Comment by kristenmills** [comment]
Yeah this was planned for scoreboard 2. I think we were just going to default to the start being the current date, and the end date being the date of the last membership entered? I never really liked the end date part of that idea, I think that at least should be configured somewhere. 

Scoreboard v1 had the concept of semesters. You created a Semester and the semester had a start and end date and memberships assigned to it. Scoreboard v2 was written we were planning to amend the constitution so memberships lasted 15 weeks (or however long a semester is) after you got it. So we moved to the set a start and end date model but never came up with a good way to display that.

**Comment by 7imbrook** [comment]
Moved to feature dev
