### ISSUE TITLE
Inconsistent headers on various pages

### ISSUE THREAD

**Issue by corbanmailloux** [rit-sse/OneRepoToRuleThemAll#96]
On the [events page](https://sse.rit.edu/events), the "Events" header is clickable and is in an `<h1>` tag.
![image](https://cloud.githubusercontent.com/assets/2474463/26177377/625cfa00-3b27-11e7-9590-295b4e41ffd2.png)

On the [projects page](https://sse.rit.edu/projects), the "Projects" header is in an `<h2>` tag (and not clickable).
![image](https://cloud.githubusercontent.com/assets/2474463/26177438/9abcf9c2-3b27-11e7-9ecb-e035a2667832.png)

On the [about page](https://sse.rit.edu/about), there is no "About" header, but the "What we're all about" header is in an `<h3>` tag.
![image](https://cloud.githubusercontent.com/assets/2474463/26177488/c9560378-3b27-11e7-8d73-470a8cd2de7f.png)

The remaining pages (such as the [officers page](https://sse.rit.edu/officers)) have headers in `<h1>` tags that are not clickable. This seems like a normal default.

**Comment by vuzDylan** [comment]
How do you feel about all H2 tags that are clickable back to the current page?

**Comment by corbanmailloux** [comment]
@vuzDylan Why would you want them to be clickable? You are already on the current page, and people will just copy the address bar if they need the link. I'm not seeing the use case for the clickable headers.
Otherwise, yeah, I think a normal `<h2>` (or `h1`, your call) would make sense.

**Comment by vuzDylan** [comment]
It is useful for pages like qdb and scoreboard when someone wants to get back to /qdb when they are on like /qdb/quotes?filter

**Comment by corbanmailloux** [comment]
@vuzDylan I see. I don't think that's an intuitive usage of the header, but I can see that argument. Mostly, I just want the styling to be consistent across the pages.

**Comment by vuzDylan** [comment]
alright
